### PR TITLE
refactor: Update parameters

### PR DESCRIPTION
**Pull request by cgilbe27**
Updates buf gen properties

### CODE REVIEW

**Review by Unique-Divine — APPROVED** [review]

**Comment by Unique-Divine** [comment]
You can merge it to main. We don't use releases/v0.21 anymore

**Comment by cgilbe27** [comment]
Need releases/v0.21.x to generate all proto's (perp/spot) otherwise it causes a huge downstream issue in the web-app/ts-sdk

**Review by Unique-Divine — CHANGES_REQUESTED** [review]
The change log should not have so many changes, just 1 line

**Comment by cgilbe27** [comment]
A lot of this was prettier

**Pull request merged**
